version: "3.8"
services:
  menu_db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5431:5432"
    healthcheck:
      test: curl -s https://localhost:5432 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "${PWD}/disks/pgdata:/var/lib/postgresql/data"
      - "${PWD}/src/main/resources/init-db/init-haccp-menu-db.sh:/docker-entrypoint-initdb.d/init-haccp-menu-db.sh.sh"